import type { CapabilityGroup } from "./types";

export const capabilities: CapabilityGroup[] = [
  {
    title: "Fiscal",
    subtitle: "Emissão e apuração",
    items: [
      "NFe",
      "NFCe",
      "NFSe",
      "CTe",
      "CTe OS",
      "MDFe",
      "Entrada automática de notas",
      "Sintegra",
      "Sped Fiscal",
      "Sped Contribuições",
      "Bloco K",
    ],
  },
  {
    title: "Vendas",
    subtitle: "Do orçamento ao faturamento",
    items: [
      "Pedido de venda",
      "Ordem de serviço",
      "Orçamento e condicional",
      "Venda externa e futura",
      "Cotações e compras",
      "Geração de contratos",
      "Geração de romaneios",
      "Força de vendas",
    ],
  },
  {
    title: "Pagamentos & estoque",
    subtitle: "Caixa, PDV e giro",
    items: [
      "TEF PayGo",
      "TEF SITEF",
      "TEF Hub Elgin",
      "SEUPOS",
      "SEUPOS Hub",
      "Connect",
      "PIX dinâmico",
      "Controle de estoque",
      "Curva ABC",
      "Controle de produção",
      "Etiquetas",
      "Lote",
    ],
  },
  {
    title: "Gestão & integrações",
    subtitle: "Financeiro e conexões",
    items: [
      "Contas a pagar e receber",
      "Conciliação bancária",
      "Boleto",
      "Painel do Contador",
      "Delivery",
      "Painel do Entregador",
      "Assinador Digital",
      "Averbação",
      "WhatsApp",
      "Promoção",
      "Gerador de Relatórios",
      "Mercado Pago",
      "Avante Market",
    ],
  },
];
