import type { Addon, Plan, PlanFeatureRow } from "./types";
import { site } from "./site";

export const plans: Plan[] = [
  {
    id: "basico",
    name: "Básico",
    price: "R$ 190",
    cents: ",00",
    period: "/mês",
    description: "Emissão ilimitada de documentos fiscais",
    features: [
      "NFe, NFSe, NFCe, CTe, MDFe, CTe OS",
      "Cadastro, estoque e relatórios",
      "Pedido de venda e orçamento",
      "Gerenciador XML e Sped Fiscal",
    ],
    cta: {
      label: "Falar sobre o Básico",
      href: site.whatsappUrl,
      variant: "outline",
      external: true,
    },
  },
  {
    id: "intermediario",
    name: "Intermediário",
    price: "R$ 280",
    cents: ",00",
    period: "/mês",
    description: "Emissão ilimitada de documentos fiscais",
    featured: true,
    badge: "Mais popular",
    features: [
      "Tudo do Básico",
      "Financeiro e ordem de serviço",
      "Produção e contratos",
      "Romaneio de entregas",
    ],
    cta: {
      label: "Falar sobre o Intermediário",
      href: site.whatsappUrl,
      variant: "brand",
      external: true,
    },
  },
  {
    id: "avancado",
    name: "Avançado",
    price: "R$ 350",
    cents: ",00",
    period: "/mês",
    description: "Emissão ilimitada de documentos fiscais",
    features: [
      "Tudo do Intermediário",
      "Pedido de compra",
      "Boleto integrado",
      "Averbação",
    ],
    cta: {
      label: "Falar sobre o Avançado",
      href: site.whatsappUrl,
      variant: "outline",
      external: true,
    },
  },
  {
    id: "premium",
    name: "Premium",
    price: "R$ 420",
    cents: ",00",
    period: "/mês",
    description: "Emissão ilimitada de documentos fiscais",
    features: [
      "Tudo do Avançado",
      "Sped Contribuições",
      "Suporte prioritário",
      "Pacote fiscal completo",
    ],
    cta: {
      label: "Falar sobre o Premium",
      href: site.whatsappUrl,
      variant: "outline",
      external: true,
    },
  },
];

export const planFeatureRows: PlanFeatureRow[] = [
  { label: "NFe", included: [true, true, true, true] },
  { label: "NFSe", included: [true, true, true, true] },
  { label: "NFCe", included: [true, true, true, true] },
  { label: "Cadastro", included: [true, true, true, true] },
  { label: "Relatórios", included: [true, true, true, true] },
  { label: "Estoque", included: [true, true, true, true] },
  { label: "Pedido de venda", included: [true, true, true, true] },
  { label: "Orçamento", included: [true, true, true, true] },
  { label: "Gestão de Documentos", included: [true, true, true, true] },
  { label: "Gerador de Relatórios", included: [true, true, true, true] },
  { label: "CTe", included: [true, true, true, true] },
  { label: "MDFe", included: [true, true, true, true] },
  { label: "CTe OS", included: [true, true, true, true] },
  { label: "Gerenciador XML", included: [true, true, true, true] },
  { label: "Produção", included: [false, true, true, true] },
  { label: "Ordem de serviço", included: [false, true, true, true] },
  { label: "Financeiro", included: [false, true, true, true] },
  { label: "Contrato", included: [false, true, true, true] },
  { label: "Romaneio", included: [false, true, true, true] },
  { label: "Pedido de compra", included: [false, false, true, true] },
  { label: "Boleto", included: [false, false, true, true] },
  { label: "Averbação", included: [false, false, true, true] },
  { label: "Sped Contribuições", included: [false, false, false, true] },
  { label: "Sped Fiscal", included: [true, true, true, true] },
];

export const addons: Addon[] = [
  { name: "Assinador", price: "R$ 40,00/mês", license: "Por licença" },
  { name: "Boleto", price: "R$ 40,00/mês", license: "Por licença" },
  { name: "Lote", price: "R$ 40,40/mês", license: "Por licença" },
  { name: "Promoção", price: "R$ 40,00/mês", license: "Por licença" },
  { name: "SEUPOS", price: "R$ 40,00/mês", license: "Por usuário" },
  { name: "SEUPDV", price: "R$ 40,00/mês", license: "Por usuário" },
  { name: "WhatsApp", price: "R$ 40,00/mês", license: "Por licença" },
];
